from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls import *
from edt.views import ReemplazosExcel,ReemplazosPDF,ImprimePermisoPDF,PermisoListView,BitHorasPDF,BitHorasExcel,EstadisticaPermisosExcel,EstadisticaPermisosPDF,AnuladosPDF,AnuladosExcel,DescontadosExcel,DescontadosPDF,DevueltosExcel,DevueltosPDF,ConPermisoPDF,ConPermisoExcel,ConLicenciaPDF,ConLicenciaExcel
urlpatterns = [

    # Examples:
    # url(r'^$', 'cal.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^login/','edt.views.login' ),
    url(r'^$','edt.views.index' ),
    url(r"^verpermiso/(?P<pk>\d+)/$","edt.views.verpermiso"),
    url(r"^verpermiso2/(?P<pk>\d+)/$","edt.views.verpermiso2"),
    url(r"^borralicencia/(?P<pk>\d+)/$","edt.views.borralicencia"),
    url(r"^borrarlicencia/(?P<pk>\d+)/$","edt.views.borrarlicencia"),
    url(r'^logout/','edt.views.logout' ),
    url(r'^upload/(?P<pk>\d+?)/$',"edt.views.upload" ),
    url(r'^devueltas/(?P<pk>\d+?)/$',"edt.views.devueltas" ),
    url(r'^main/(\d+)/$', "edt.views.main"),
    url(r"^comprobante/(?P<pk>\d+)/$","edt.views.comprobante" ),
    url(r"^ingresoreemplazo/(?P<pk>\d+)/$","edt.views.ingresoreemplazo" ),
    url(r'^urlcalendario/$', "edt.views.urlcalendario"),
    url(r'^wsCalendari/', "edt.views.wsCalendario"),
    url(r'^wsPermiso_Jefatura/', "edt.views.wsPermiso_Jefatura"),
    url(r'^main/', "edt.views.main"),
    url(r'^permiso/','edt.views.ingresapermiso' ),
    url(r'^permisos/','edt.views.permisos' ),
    url(r'^permisolst/','edt.views.permisolst' ),
    url(r'^resolucion/','edt.views.aprobarRechazar' ),
    url(r"^respuesta/(?P<pk>\d+)/$","edt.views.mostrar_respuesta" ),
    url(r'^genero/','edt.views.wsGenero' ),
    url(r'^jefaturas/','edt.views.wsJefaturas' ),
    url(r'^permiso_jefatura/','edt.views.permiso_jefatura' ),
    url(r'^licencia/$','edt.views.licencia' ),
    url(r'^ConLicencia/$','edt.views.ConLicencia' ),
    url(r'^comprobantelicencia/(?P<pk>\d+?)/$',"edt.views.comprobantelicencia" ),
    url(r'^conlicenciaPDF/',ConLicenciaPDF.as_view()),
    url(r'^conlicenciaEXCEL/$',ConLicenciaExcel.as_view(), name="ConLicenciaExcel"),
    url(r'^edades/','edt.views.wsEdades' ),
    url(r'^bitacora/', PermisoListView.as_view()),
    #url(r'^modpermiso/', PermisoUpdateView.as_view()),
    url(r'^anularlst/','edt.views.anularlst' ),
    url(r"^anulapermiso/(?P<pk>\d+)/$","edt.views.anulapermiso"),
    url(r'^anula/','edt.views.anula'),
    url(r"^anulado/(?P<pk>\d+)/$","edt.views.mostrar_anulado" ),    
    url(r'^horas/', "edt.views.horas"),
    url(r"^devolver/","edt.views.devuelvehoras"),
    url(r"^descontar/","edt.views.descontar"),
    url(r'^bgeneral/', "edt.views.bitgeneral"),
    url(r'^anulaciones/', "edt.views.anulaciones"),
    url(r'^bfuncionario/',"edt.views.bitfuncionario"),
    url(r'^reemplazolicencia/',"edt.views.reemplazolicencia"),
    url(r'^rl/',"edt.views.rl"),
    url(r'^InformeReemplazos/',"edt.views.InformeReemplazos"),
    url(r'^reemplazos/$',"edt.views.reemplazoslst"),
    url(r'^reemplazosPDF/',ReemplazosPDF.as_view()),
    url(r'^reemplazosEXCEL/$',ReemplazosExcel.as_view(), name="ReemplazosExcel"),
    url(r'^permisosusuario/(?P<pk>\d+)/$',"edt.views.permisosusuario"),
    url(r'^imprimepermiso/',ImprimePermisoPDF.as_view()),
    url(r'^bhorasEXCEL/$',BitHorasExcel.as_view(), name="BitHorasExcel"),
    url(r'^bhorasPDF/',BitHorasPDF.as_view()),    
    url(r'^bhoras/',"edt.views.bithoras"),
    url(r'^anuladosEXCEL/$',AnuladosExcel.as_view(), name="AnuladosExcel"),
    url(r'^anuladosPDF/',AnuladosPDF.as_view()),
    url(r'^anulados/','edt.views.anulados' ),
    url(r'^descontadosEXCEL/$',DescontadosExcel.as_view(), name="DescontadosExcel"),
    url(r'^descontadosPDF/',DescontadosPDF.as_view()),
    url(r'^descontados/','edt.views.descontados' ),
    url(r'^devueltosEXCEL/$',DevueltosExcel.as_view(), name="DevueltosExcel"),
    url(r'^devueltosPDF/',DevueltosPDF.as_view()),
    url(r'^devueltos/','edt.views.devueltos' ),
    url(r'^estadisticapermisosPDF/',EstadisticaPermisosPDF.as_view()),
    url(r'^estadisticapermisosEXCEL/$',EstadisticaPermisosExcel.as_view(), name="EstadisticaPermisosExcel"),
    url(r'^estadisticapermisos/',"edt.views.EstadisticaPermisos"),
    url(r'^gpermisos/','edt.views.GraficoPermisos' ),
    url(r'^conpermiso/','edt.views.ConPermiso' ),
    url(r'^conpermisoPDF/',ConPermisoPDF.as_view()),
    url(r'^conpermisoEXCEL/$',ConPermisoExcel.as_view(), name="ConPermisoExcel"),
    url(r'^funcevento/','edt.views.funcionarioEvento' ),
    url(r'^licencia/validar/$', "edt.views.validalicencia", name='validalicencia'),
    url(r'^UsuarioAPI/$',"edt.views.UsuarioAPI"),
    url(r'^LicenciaAPI/$',"edt.views.LicenciaAPI"),
    url(r'^ReemplazoAPI/$',"edt.views.ReemplazoAPI"),







    # url(r'^(?P<slug>[-\w]+)/$', PermisoDetailView.as_view(), name='permiso-detail'),

]
